export interface Video {
  title: string;
  id: string;
}

export const videosByLetter: Record<string, Video[]> = {
  a: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "iwNZy5kCGHQ" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "XtgaNu8tI-c" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "g0TTKJcIYaE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Hxr0FwKzoFc" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "l71ax_eK6qA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "LgcaaPq_EnE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "d-MFB1QF5gM" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "6d_vRTMyjlg" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "23YP7OOXhkY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "XdYTItXlxl4" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "kM66DK9woiI" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "9APHwVrewps" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "NXE3bjLAuCw" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "79p3fIkigB0" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "G4MLq5xx6P0" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "_tuURDV2iD4" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "KP17TeLVvUQ" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "8C2JSiJzd_c" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "K3eeyjEkDKA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "L-h3KMo0VrU" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "q3-96xbPyHw" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "YUmkSHzB6y8" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "iq91kIxgBrs" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "sEVBXvB_liY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "1tbHZIj3gXA" },
  ],
  b: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "H0INpWW8Fr0" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "m0SFIq4PCC4" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "BWSD5NDmzp0" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "mfzOtgr3PTs" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "-3u52f9-hLc" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "jKlg-pwCCl4" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "I9iMhBU2yu4" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "yexxn7-NhIk" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Enz7Xt0mPe8" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "dk-HyHHPfhM" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "XnqUxo5tvRQ" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "W1nqFgLGPd4" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "sgCDfxJVSVE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Kh0qDdaWFtE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "iAB1auM_3D8" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "3ociXmg1GCM" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "FWTyX6DXc8A" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "tt6rAAODtps" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "YiSrr2ZSi8w" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "uQK7zZh6x_4" },
  ],
  c: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "8N8NAOMvRs4" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "tIkim2R41VI" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "YbuzI7eymj8" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "SwyUaDJkCi8" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "i5vd6Z_gOJE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "2a2B_NCf-Vs" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "7EKMVjn9tLc" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "aXPPXYJu9k8" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "x36q0veCYQY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "pNWpRC_UTi4" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "PrrbnGYp_eY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "XecPSPMi5dw" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "ZdigceB8FyQ" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "7QaRImi2R6s" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "2rjexD-TkRs" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "jFzW-aTVuAY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "PzzZXgBV2VY" },
  ],
  d: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "hu-26VpP3QM" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "3MpwvpXOshw" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "rjDZEvtniOQ" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "d-q0L-FUTQ8" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "v3olL7UoI_k" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "gei4X6EXkog" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "fDSyGvEBZLo" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "tYU2qnu-l5s" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "7X91ubKk0D8" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "RoRw5xFtg4Q" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "PCTx-FeK2Xk" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "m4nSDRrSDrw" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "qwAGdwGg5hk" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "6-Udz-gva2Y" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "RDL9yfcs0OI" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "PVEhmxcqu6Y" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "wYJ21V1Ocnc" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "PiKtZYq_J4M" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "f2SxvVHSL88" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "gO-nKxPgEO0" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "VCUd9HtHwBM" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "cqJUdS_sCxw" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "qi6MmSEkPuE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "laoOUa4ttwM" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "geY0k1j8rxg" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "_a1Ilp5IcEY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "be08GkZGz9c" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "a6XMNOpfAMI" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "7SLB0KL4ZFo" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "iyit4fp0dsM" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "6OootbYwfOQ" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "OXOftv5a5eE" },
  ],
  e: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "yw5eFoSj8_Q" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "6am_aZwb2vU" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "mZJ_cnSaRME" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "YjK6WTorI5w" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "8NF1CfDh5m8" },
  ],
  f: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "f3DCNuOPerI" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "KmJaaawzu5s" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "kYQezNQ4-YA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "IhOu3q8wFpY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "5RdmhbAClro" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "xO61dFM_hy0" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "dAHBoJAL4j0" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Gr65RZCitgA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "sbeiMZDCLrk" },
  ],
  g: [
    { title: "Garbage Live in Toronto 2015", id: "gZQYskWrZOU" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "CUu5JjZui4I" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "auF-Y8lbotI" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "CdztlbgQ3lM" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "icyQN_QcCrs" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "-Ma0AOIb8CQ" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "rqnZi3ZrjQs" },
  ],
  h: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "5ZeN9G1zv7I" },
    { title: "Hatebreed Destroy Everything Toronto Kool Haus January 9, 2015", id: "oXwyYzt3yOI" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "T6UPeh6frZ8" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "cWzVgD6g0Dg" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "E3MF7NwcYPA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "6vB417WNFi4" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "tqSQIM2qJPY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "J0_JNjfhozI" },
  ],
  i: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "rCbJ-AMD21k" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "Bs3LyCzS_xA" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "aqFI4_XpWkI" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "GmyerBC0RxI" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "4A9E6T9m9hU" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "fu0-wHjasLA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "CQ8i5I2YWhk" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Gr65RZCitgA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "gNadTTxHga8" },
  ],
  j: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "AKpahuw40zA" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "WxkdYy_4GGw" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "vvN8vIfO14o" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "fSnyuWST-mE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "P2T7pfLYV2o" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Ckym9O0L9Q0" },
  ],
  k: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "WRsyazedzEQ" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "FmOw_IQRw9s" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "uqAs1t41z_g" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "yDCWbPEGkuw" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "M5N4vOsuDdk" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "L2thH_YQ2sY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "lrW7V87L5AQ" },
  ],
  l: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "3LpmJsbj_1U" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "PzBIXpDsPis" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "EceWg_2neSQ" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "hyHqkGTCnEM" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "-gU_BkVIWh8" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "zX5Z1XXgGpA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "PixdWPVnfEY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "wF22csx97WA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "sedLCjW1Q70" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "PWsZtdwvfVY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "es1C4pkb2-g" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "KLxmCsMHQBk" },
  ],
  m: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "QI4cmQ-oX60" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "uW4fTYb2JdE" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "tp71f-hKCsI" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "cmXFqUQjOuI" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "J3_R0qPQw18" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "iFCIVlCSPLI" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "wBZVDQQchMA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Gr65RZCitgA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "zviBGOI2KL8" },
  ],
  n: [],
  o: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "dYSBG-gehyY" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "IiqMCVG_GoM" },
  ],
  p: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "eQyTlP0ZhAI" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "DLAkPoy-9Qs" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "d2OatkDlvtY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "456VnYRSaiA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "0kIpUFxDzL0" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Hkx3iv6nEJU" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "L1uPbkSo6xU" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "LzSNjgHI62g" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "xsKe3A9YhV0" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "k8z8A4obnZA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Ctq6ETUzTIk" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Xj1za1XPDv0" },
  ],
  q: [],
  r: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "y8cIBJxjD1E" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "yTiFQIDPe3A" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "tKtu2D-vJDo" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "p7Pc0_0eTps" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "WjqwcHBoI6Q" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "zyL1ySj0ZTU" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Gr65RZCitgA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "a6XMNOpfAMI" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "CkhLx_503MU" },
  ],
  s: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "gWV6a5aYd80" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "EacwM6PLTrY" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "-fThjMklApA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "aGn_G47kFRE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "U6FypNKVQss" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "yqqy__naqwM" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "mh9iRYbj8jE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "5skthg8uwxs" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "c7m3TStU8TI" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "-AGME5kv2sU" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "LGblQpyN8vA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Gld-TPVFzsg" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "8-zJAeOgvPY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "ZzY8X4mJPNc" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "a6-4hpJx7IU" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "qsZPRjDBQ80" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "F7YEF20Oewk" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "LbT3Jzy_w5Y" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "dk26VrhMDcQ" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "gOJhheiJZbY" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "P70krhYxVp4" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "1Jyjy4HYiDM" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Zm4mtL882DU" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "wR6DQLzs9bI" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "9CFXNZyXGjo" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "HAv4RXTGmQs" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "8Ry0SgceUvc" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "KtGck0CJfDQ" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "YojekL72A8s" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "7W1Gnouyw_M" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "zA0iAF6nwkc" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "QAWyuhvZUbQ" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "LtYLYIP6_BM" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "JAlwSU7pTkQ" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "8vvpscuw7FE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "7JY1Vpg3xtM" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "vDeRNqD27LU" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "dX5GbStb2C4" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "P4vyzWT1Zt4" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "fyiDPnnUxVk" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "U8TzNXV820Y" },
  ],
  t: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "bNUL0IgCn2I" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "6q7f7O7ioaA" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "jRs5k4gFwn4" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "HGOyA0l-zJE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "jVSQGdvgKaE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "i5rfRErForw" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "QOyI0LyG9dw" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "a0qZYYnXZwE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "5RZlLcc0JJw" },
  ],
  u: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "iwNZy5kCGHQ" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "XtgaNu8tI-c" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "g0TTKJcIYaE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "Gr65RZCitgA" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "4Fx23g1PfJo" },
  ],
  v: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "E7TdalvhL9Q" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "bLVLyQMluXY" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "4Fx23g1PfJo" },
  ],
  w: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "OcsnpG7CZ_w" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "I8hG8nT2N6g" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "xnVkCneMwRE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "-MJM9HZfIsE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "1SygbIpeuC8" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "EhpHGT7B4xo" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "nDko2gg6LFM" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "vGiwxyiNwKc" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "ER0p-hc_AHg" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "R-M_sLx4AU4" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "sxG959a3SpE" },
    { title: "Rock and Roll Canada Video Lee Aaron", id: "-BB8YAuLbjE" },
  ],
  x: [
    { title: "Anti Queens Live New Years at Bovine Sex Club", id: "JGHd3VyT8UI" },
    { title: "Ladders Anti Queens at Bovine Sex Club", id: "Gr65RZCitgA" },
    { title: "Anti Queens New Years Eve Bovine Sex Club", id: "QKFVKkCfowc" },
  ],
  y: [],
  z: [],
};

export const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

export function getVideosForLetter(letter: string): Video[] {
  return videosByLetter[letter.toLowerCase()] || [];
}
